package com.nomoskeeters.sensor

import com.nomoskeeters.sensor.protocol.FramePacket
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Verifies the Kotlin frame packer produces bytes identical to what the PC's
 * `phone_sensor.protocol.parse_frame_packet` expects. The golden hex below was
 * generated by the Python side (`pack_frame_packet`) for the same inputs, so a
 * match proves cross-language wire compatibility down to the byte.
 */
class FramePacketTest {

    /** Python golden: FramePacket(7, 123456789, "main", "nv21", 4, 4, range(24)). */
    private val golden =
        "4e4d5331070000000000000015cd5b07000000000400040004000400180000006d61696e6e763231" +
        "000102030405060708090a0b0c0d0e0f1011121314151617"

    @Test
    fun packsByteIdenticalToPythonGolden() {
        val payload = ByteArray(24) { it.toByte() }
        val packed = FramePacket.pack(
            frameId = 7L,
            captureTsUs = 123_456_789L,
            cameraId = "main",
            fmt = "nv21",
            width = 4,
            height = 4,
            payload = payload,
        )
        assertEquals(golden, packed.toHex())
    }

    @Test
    fun headerIsThirtyTwoBytesPlusStringsPlusPayload() {
        val packed = FramePacket.pack(1L, 2L, "x", "h264", 1920, 1080,
            byteArrayOf(0xAA.toByte(), 0xBB.toByte(), 0xCC.toByte()))
        // 32 header + 1 ("x") + 4 ("h264") + 3 payload = 40.
        assertEquals(40, packed.size)
        assertTrue(packed.toHex().startsWith("4e4d5331")) // "NMS1"
    }

    private fun ByteArray.toHex(): String =
        joinToString("") { "%02x".format(it.toInt() and 0xFF) }
}
