package com.nomoskeeters.sensor

import com.nomoskeeters.sensor.protocol.FramePacket
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Verifies the Kotlin frame packer produces bytes identical to what the PC's
 * `phone_sensor.protocol.parse_frame_packet` expects. The golden hex below was
 * generated by the Python side (`pack_frame_packet`) for the same inputs, so a
 * match proves cross-language wire compatibility down to the byte.
 */
class FramePacketTest {

    /** Python golden: FramePacket(7, 123456789, "main", "nv21", 4, 4, range(24))
     *  with the default chunk_index=0, chunk_count=1 (unfragmented). */
    private val golden =
        "4e4d5332070000000000000015cd5b070000000004000400040004001800000000000100" +
        "6d61696e6e763231000102030405060708090a0b0c0d0e0f1011121314151617"

    @Test
    fun packsByteIdenticalToPythonGolden() {
        val payload = ByteArray(24) { it.toByte() }
        val packed = FramePacket.pack(
            frameId = 7L,
            captureTsUs = 123_456_789L,
            cameraId = "main",
            fmt = "nv21",
            width = 4,
            height = 4,
            payload = payload,
        )
        assertEquals(golden, packed.toHex())
    }

    @Test
    fun headerIsThirtySixBytesPlusStringsPlusPayload() {
        val packed = FramePacket.pack(1L, 2L, "x", "h264", 1920, 1080,
            byteArrayOf(0xAA.toByte(), 0xBB.toByte(), 0xCC.toByte()))
        // 36 header + 1 ("x") + 4 ("h264") + 3 payload = 44.
        assertEquals(44, packed.size)
        assertTrue(packed.toHex().startsWith("4e4d5332")) // "NMS2"
    }

    @Test
    fun chunkOfAFrameCarriesIndexCountAndItsSlice() {
        // Second of three chunks: payload slice [4,8), chunk_index=1, count=3.
        val payload = ByteArray(12) { it.toByte() }
        val packed = FramePacket.pack(
            frameId = 9L, captureTsUs = 0L, cameraId = "x", fmt = "h264",
            width = 1, height = 1, payload = payload,
            payloadOffset = 4, payloadLen = 4, chunkIndex = 1, chunkCount = 3)
        // 36 header + 1 + 4 + 4 payload = 45.
        assertEquals(45, packed.size)
        // chunk_index/chunk_count occupy the last 4 header bytes (indices 32..35).
        val hex = packed.toHex()
        assertEquals("01000300", hex.substring(64, 72)) // index=1, count=3 (LE u16)
    }

    private fun ByteArray.toHex(): String =
        joinToString("") { "%02x".format(it.toInt() and 0xFF) }
}
